name: Repository Secret Template

on:
  push:

permissions:
  contents: read

jobs:
  use-repository-secret:
    runs-on: ubuntu-latest

    env:
      FLAG: ${{ secrets.FLAG }}

    steps:
      - name: Use repository secret
        shell: bash
        run: |
          echo "The secret FLAG is: $FLAG"
